### ISSUE TITLE
A few problems

### ISSUE THREAD

**Issue by jake-g** [NachtRaveVL/Lepton-FLiR-Arduino#1]
I have a teensy 3.6 and a flir v1.4 module and am trying to send the frame pixels over serial and plot in python.

`setSysTelemetryEnabled` is not defined in the library, so the     `flirController.setSysTelemetryEnabled(ENABLED); ` does not work. I'm not really sure what this even does. commenting out the above telemetry line lets me run some of the examples

thanks

**Comment by jake-g** [comment]
fixed some of this

**Comment by derekwacks** [comment]
In the library file LeptonFLiR.h, it's defined as
 `void sys_setTelemetryEnabled(bool enabled);`
so the line in the adv. example should be changed to
`flirController.sys_setTelemetryEnabled(ENABLED); `

**Comment by NachtRaveVL** [comment]
Oh wow, thanks for the heads up. If you’d like to make a pull request for this I’d really love the help, otherwise I will make one later today when I get back home from work.

Thanks for the interest!

I do ask tho, have you been able to get it to work on a teensy 3.6? I have one as well, I should probably try it out and see if the software copy is fast enough with it.

**Comment by derekwacks** [comment]
There should be an open pull request from @samyk that resolves it. I hadn't tried it on a teensy, though I might have one laying around to test it. I connected it to an arduino Mega, but realized there isn't enough capacity to capture a full frame, so I'm switching to a rPi 
Thank you so much for the library!
